global:
  scrape_interval: 30s 


scrape_configs:
  # Prometheus itself
  # This uses the static method to get metrics endpoints
  - job_name: "prometheus"
    honor_labels: true
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: node 
    static_configs:
      - targets: ["192.168.144.1:9100"]
  - job_name: 'todo-api'
    static_configs:
      - targets: [ '192.168.1.68:4001' ]
        labels:
          job: todo-api
          app: todo-api
          env: dev
