// Code generated by goctl. DO NOT EDIT.
package types

type ToggleTodoReq struct {
	Id        string `json:"id"`
  Description string `json:"description"`
	Completed bool   `json:"completed"`
}

type Todo struct {
	Id          string `json:"id"`
	Description string `json:"description"`
	Completed   bool   `json:"completed"`
}

type GetTodoReq struct {
	Id string `path:"id"`
}

type RespStatus struct {
	Status  int64  `json:"status"`
	Message string `json:"message"`
}
