// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"
	"time"

	"github.com/sansayin/todo-zero/todo/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/todo",
				Handler: getTodosHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/todo/:id",
				Handler: getTodoHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/todo",
				Handler: createTodoHandler(serverCtx),
			},
			{
				Method:  http.MethodPut,
				Path:    "/todo",
				Handler: toggleTodoHandler(serverCtx),
			},
			{
				Method:  http.MethodDelete,
				Path:    "/todo",
				Handler: deleteTodosHandler(serverCtx),
			},
		},
		rest.WithTimeout(3000*time.Millisecond),
	)
}
